import discord
from discord.ext import commands

#creates the client
client = commands.Bot(command_prefix='/')

#This event makes sure that the bot is online
@client.event
async def on_ready():
    print('Bot is online!')

client.run('')#recieves the token generated by discord. This token will be regenerated.